Repository RaidAndFade/HacktoberChallenges, pull requests merged in 2018-10, with the labels that each got.

#60 Created person friend file
  Friends/CohheeTime.html
Labels: invalid

#63 Add santatra.html
  Friends/nirinarisantatra.html
  Friends/santatra.html
Labels: invalid

#98 Create raidandfade.html
  Friends/raidandfade.html
Labels: invalid

#96 File
  Friends/thresher25.html
Labels: autochecked

#86 added myself to the friends list
  Friends/jenniedalgren.html
Labels: autochecked

#87 Added moi.
  Friends/Recursivepaiste.html
Labels: autochecked

#89 Hello world
  Friends/thomas0306.html
Labels: autochecked

#90 create ynnk1 as new friend
  Friends/ynnk1.html
Labels: autochecked

#91 added my page!! wooty tooty
  Friends/hurleyandrew.html
Labels: autochecked

#92 created dansegliode.html
  Friends/dansegliode.html
Labels: autochecked

#93 Added name and profile link
  Friends/thvardhan.html
Labels: autochecked

#94 Created AineshSootha.html
  Friends/AineshSootha.html
Labels: autochecked

#97 added gitKendra html file
  Friends/gitKendra.html
Labels: autochecked

#82 Create Damianson.html
  Friends/Damianson.html
Labels: autochecked

#84 create sahaj.html
  Friends/Sahaj-Bamba.html
Labels: attention

#81 Create Bottersnike.html
  Friends/Bottersnike.html
Labels: attention

#78 Adding Vladyslav's html
  Friends/SrVladyslav.HTML
Labels: attention

#101 Added a friend page.
  Friends/TileThePlane.html
Labels: attention

#102 Happy Hacktoberfest
  Friends/sr229.html
Labels: autochecked

#108 Added myself!
  Friends/carolinajimenez26.html
Labels: attention

#106 for the sake of my hacktoberfest 2018
  Friends/suksest.html
Labels: attention

#105 bugfix typo
  Friends/minnimimi.html
Labels: attention

#119 Tonetheman
  Friends/tonetheman.html
Labels: autochecked

#114 Added glorious html file
  Friends/Fraaankes.html
Labels: autochecked

#120 Added nickxla page :shipit:
  Friends/nickxla.html
Labels: attention

#117 add Dharmesh Poddar
  Friends/Dharmesh-Poddar.html
Labels: attention

#111 Create lchaglla.html
  Friends/lchaglla.html
Labels: attention

#122 Added hmccree to friends
  Friends/hmccree.html
Labels: attention

#121 Added alejandra-gonzalez.html
  Friends/alejandra-gonzalez.html
Labels: attention

#125 Add randomization.html
  Friends/randomization.html
Labels: autochecked

#126 my profile
  Friends/syauqiahmd.html
Labels: attention

#127 Hi I have changed html and I fixed errors
  Friends/xavidotcat.html
Labels: attention

#129 added my page
  Friends/samyak-sopho.html
Labels: attention

#128 Create bl4ckp4nther.html
  Friends/bl4ckp4nther.html
Labels: autochecked

#124 Create fuj1n.html
  Friends/fuj1n.html
Labels: autochecked

#131 Added geniusmehul as your friend!
  Friends/geniusmehul.html
Labels: autochecked

#132 added my profile
  Friends/gettaplay.html
Labels: attention

#137 added friend Pavel
  Friends/pavelisp.html
Labels: attention

#135 Added my webpage
  Friends/dcox2016.html
Labels: attention

#130 Create blindingstars.html
  Friends/blindingstars.html
Labels: attention

#136 Add TravelingMan to the growing pile of friends
  Friends/TravelingMan.html
Labels: attention

#139 Added html file to friends
  Friends/siddhantapanda77.html
Labels: autochecked

#142 added mi html page
  Friends/eagleera.html
Labels: attention

#143 Hi, I added my new page
  Friends/HenD-11.html
Labels: attention

#157 Add Vatsal
  Friends/vattytrivedi.html
Labels: autochecked

#155 Create samfromguam.html
  Friends/samfromguam.html
Labels: autochecked

#154 Create Joulay.html
  Friends/Joulay.html
Labels: autochecked

#148 Added my name to friends list
  Friends/lakme22.html
Labels: autochecked

#158 Added my name to friends list
  Friends/thirulak.html
Labels: autochecked

#166 Create Codemasters23
  Friends/Codemasters23.html
Labels: attention

#164 Create vRezn0v.html
  Friends/vRezn0v.html
Labels: attention

#163 profile added
  Friends/Shenr0n.html
Labels: attention

#161 Add Friend
  Friends/chetanag35.html
Labels: attention

#160 Added Myself :D
  Friends/Casey-McCray.html
Labels: attention

#156 Added myself, Mohammed532
  Friends/Mohammed532.html
Labels: attention

#147 Added a new html file with my greetings.
  Friends/lihofm.html
Labels: attention

#169 Created SudhiMohan.html
  Friends/SudhiMohan.html
Labels: autochecked

#171 Create ytmnd.html
  Friends/ytmnd.html
Labels: autochecked

#152 Add andy-kohne as a friend
  Friends/andy-kohne.html
Labels: attention

#172 friends html
  Friends/carlosgub.html
Labels: attention

#167 Added silvericarus.html to Friends folder
  Friends/silvericarus.html
Labels: attention

#145 Added myself
  Friends/TheNoodleMoose.html
Labels: needs work

#174 Create trillcosby.html
  Friends/trillcosby.html
Labels: autochecked

#180 Add files via upload
  Friends/adlyloukil.html
Labels: autochecked

#183 add jennparker.html to Friends
  Friends/jennparker.html
Labels: attention

#182 added new friend page
  Friends/steroyle.html
Labels: attention

#176 Add hercegtomas.html to Friends
  Friends/hercegtomas.html
Labels: attention

#153 Add New Friend :ok_hand:
  Friends/AdnanMuhib.html
Labels: attention

#206 Added RonLek.html
  Friends/RonLek.html
Labels: autochecked

#203 Added myself
  Friends/mayukh45.html
Labels: autochecked

#187 Yo yo!
  Friends/chris-luafau.html
Labels: autochecked

#185 Added myself!
  Friends/Exorust.html
Labels: autochecked

#181 Create rbcunhadesign.html
  Friends/rbcunhadesign.html
Labels: autochecked

#179 Create lakshyabatman.html
  Friends/lakshyabatman.html
Labels: autochecked

#205 Ph PR
  Friends/phillipesouza.html
Labels: autochecked

#209 new html file
  Friends/Tharuja.html
Labels: autochecked

#210 Please accept me!
  Friends/vaticori.html
Labels: autochecked

#190 Create SacitKuheylan.html
  Friends/SacitKuheylan.html
Labels: autochecked

#217 add my page
  Friends/annsv.html
Labels: autochecked

#214 my submission
  Friends/PinkiePie1189.html
Labels: autochecked

#195 Created Xabifk.html
  Friends/Xabifk.html
Labels: attention

#219 I'm here :D
  Friends/sdersc.html
Labels: attention

#218 Added friend!
  Friends/CatherineEtter.html
Labels: attention

#212 Created Tilak-Shenoy.html
  Friends/Tilak-Shenoy.html
Labels: attention

#211 My page html for make friends
  Friends/liooh.html
Labels: attention

#213 this is mal pull.... request
  Friends/lucioleandro.html
Labels: attention

#208 Added a new friend
  Friends/ktopouzi.html
Labels: attention

#207 pepper-seattle friend html hacktober2018 commit
  Friends/pepper-seattle.html
Labels: attention

#204 Hello world
  Friends/afro-code.html
Labels: attention

#199 Add Matheus Barros
  Friends/bmatheus91.html
Labels: attention

#196 Create SloRunner.html
  Friends/SloRunner.html
Labels: needs work

#220 Add friend Danilo
  Friends/danherrera.html
Labels: attention

#223 Add mysql as a friend
  Friends/maria-noel.html
Labels: attention

#224 Added Exoceus as a Friend
  Friends/Exoceus.html
Labels: attention

#225 Create rocarft.html
  Friends/rocarft.html
Labels: attention

#231 add hilmi biya
  Friends/hilmibiya.html
Labels: autochecked, week1

#222 thanks raid
  Friends/cakedan.html
Labels: attention, week1

#221 My Github Page
  Friends/arnavpisces.html
Labels: attention, week1

#235 add html file to Friends folder
  Friends/EduLara97.html
Labels: autochecked, week1

#240 added rock paper scissors game
  Games/yuibun/index.html
  Games/yuibun/main.css
  Games/yuibun/main.js
Labels: attention, week2

#241 ryanc16 - Created Halloween memory matching game
  Games/ryanc16/index.html
  Games/ryanc16/main.css
  Games/ryanc16/main.js
Labels: attention, week2

#229 update link github rizkimufti
  Friends/rizkimufti.html
Labels: attention

#242 request to be re-judged
  Friends/HasangaLakdinu.html
Labels: attention, week1

#245 Once again my profile card
  Friends/Simply007.html
Labels: needs work, week1

#246 added link to previous html file
  Friends/djsdvg.html
Labels: autochecked, week1

#239 Create ChangeColor.html
  Friends/PriyamAgrawal.html
Labels: needs work, week1

#255 added-sunk44-in-friends
  Friends/sungk44.html
Labels: attention, week1

#257 I love to meet new people!
  Friends/C-Bouthoorn.html
Labels: attention, week1

#253 added hi-manshu-kumar
  Friends/hi-manshu-kumar.html
Labels: attention, week1

#249 Add memory game.
  Games/edpen/index.html
  Games/edpen/main.css
  Games/edpen/main.js
Labels: attention, week2

#260 Add pong game
  Games/nik1082/index.html
  Games/nik1082/main.css
  Games/nik1082/main.js
  contributors.md
Labels: attention, week2

#261 added ryanc16 (self) to contributors.md
  contributors.md
Labels: attention

#264 add JanuriDP
  Friends/JanuriDP.html
Labels: needs work, week1

#262 Typo Changes
  Friends/nikzayn.html
Labels: attention, week1

#263 Added simple flyer game
  Games/mevrouwdevries/index.html
  Games/mevrouwdevries/main.css
  Games/mevrouwdevries/main.js
Labels: attention, week2

#265 Add another snake game
  Games/JanuriDP/index.html
  Games/JanuriDP/main.js
Labels: attention, week2

#266 added html page
  Friends/darrenrector91.html
Labels: attention, week1

#268 Senpai Raid notice me
  Friends/sr229.html
Labels: attention

#269 adding my name
  contributors.md
Labels: attention

#270 Adding my awesome search box.
  Games/gilann/index.html
  Games/gilann/search.css
Labels: attention, week2

#271 sami286 game added
  Games/sami286/index.html
  Games/sami286/main.css
  Games/sami286/main.js
Labels: attention, week2

#276 completed issue #1
  Friends/emilycolon.html
Labels: attention, week1

#278 Update contributors.md
  contributors.md
Labels: attention

#279 Adding snake game
  Games/tomerpacific/index.html
  Games/tomerpacific/main.css
  Games/tomerpacific/main.js
Labels: attention, week2

#284 Added myself
  contributors.md
Labels: attention

#285 Adds new friend
  Friends/remigioamc.html
Labels: attention, week1

#292 added file in friends
  Friends/komal180.html
Labels: autochecked, week1

#305 Add myself as a contributor
  contributors.md
Labels: attention

#303 Added myself to Challenge Participants
  contributors.md
Labels: attention

#301 Create IamGauravSaini.html
  Friends/IamGauravSaini.html
Labels: attention, week1

#287 Challenge #2
  Games/andy-kohne/index.html
  Games/andy-kohne/main.css
  Games/andy-kohne/main.js
Labels: attention, week2

#288 Hello From TVK
  Games/trumvekhuya/index.html
  Games/trumvekhuya/main.css
  Games/trumvekhuya/main.js
Labels: attention, week2

#290 Added a color guessing game
  Games/Rahul-Vijay/index.html
  Games/Rahul-Vijay/main.css
  Games/Rahul-Vijay/main.js
Labels: attention, week2

#294 Update contributors.md
  contributors.md
Labels: attention

#307 Added animal-themed memory game
  Games/connyheb/index.html
  Games/connyheb/main.css
  Games/connyheb/main.js
  contributors.md
Labels: attention, week2

#299 Added myself to challenge participant's list
  contributors.md
Labels: attention

#298 Update contributors.md
  contributors.md
Labels: attention

#297 Update contributors.md
  contributors.md
Labels: attention

#295 Waana be a contributor
  contributors.md
Labels: attention

#291 Update contributors.md
  contributors.md
Labels: attention

#310 Added:bounce eater game,name to contributors.md
  Games/11A11/index.html
  Games/11A11/main.css
  Games/11A11/main.js
  contributors.md
Labels: needs work, week2

#313 Adding myself to contributors
  contributors.md
Labels: attention

#319 obstacle game
  Games/kumaran-14/index.html
  Games/kumaran-14/main.css
  Games/kumaran-14/main.js
Labels: attention, week2

#316 added whack-a-mole game
  Games/sohail764245/index.html
  Games/sohail764245/main.css
  Games/sohail764245/main.js
  contributors.md
Labels: attention, week2

#315 Update contributors.md
  contributors.md
Labels: attention

#309 Added shannonmook.html file to FRIENDS folder
  Friends/shannonmcook.html
Labels: attention, week1

#293 Create game 'fuj1n'
  Games/fuj1n/index.html
  Games/fuj1n/main.css
  Games/fuj1n/main.js
Labels: attention, week2

#314 new game added
  Games/nitinrohra/index.html
  Games/nitinrohra/main.css
  Games/nitinrohra/main.js
Labels: attention, week2

#329 Update contributors.md
  contributors.md
Labels: attention

#337 give me my file back!!!
  Friends/ncplayz.html
Labels: attention, week1
