Repository RaidAndFade/HacktoberChallenges, pull requests merged in 2018-11, with the labels that each got.

#578 Create hello_world.cs
  HelloWorld/hello_world.cs
Labels: attention, week4

#599 Windows 10 style BSOD
  BSoD/casman300.html
Labels: attention, week3

#594 Update contributors.md
  contributors.md
Labels: attention, contriblist

#608 Update contributors.md, added name to contributers
  contributors.md
Labels: attention, contriblist

#600 Add new friend to /Friend
  Friends/techtolentino.html
Labels: attention, week1
